### PR TITLE
changes to always insert dafault license in create course and not exp…

### PR DESCRIPTION
**Pull request by szgooru**
…ect from API payload

### CODE REVIEW

**Comment by am-gooru** [comment]
@szgooru 

Do we want to remove the license from insertable fields list as well?

**Comment by szgooru** [comment]
What about update course? We also do not allow it from update course right?

**Comment by szgooru** [comment]
@am-gooru 
Removed license from insertable and updatable fields. Please merge.

**Comment by am-gooru** [comment]
:thumbsup:

**Pull request merged**
